"""
attribution.py - Shapley-value based contribution modeling.

Accurately attributes credit for an outcome (conversion, revenue, performance KPI)
across N contributing factors using the game-theoretic Shapley framework.
Works for: marketing attribution, feature contribution, team/agent attribution.
"""

import numpy as np
import pandas as pd
from itertools import combinations
from typing import Callable, List, Dict


def shapley_values(players: List[str],
                   characteristic_fn: Callable[[frozenset], float],
                   n_samples: int = 512,
                   seed: int = 42) -> Dict[str, float]:
    """
    Monte-Carlo Shapley value estimation.

    players           - list of contributing entities (channels, features, agents)
    characteristic_fn - v(S) -> float: value generated by coalition S
    n_samples         - permutation samples (exact for |players| <= 10, MC otherwise)
    returns           - dict mapping each player to its fair-share attribution
    """
    rng = np.random.default_rng(seed)
    n = len(players)
    shapley = {p: 0.0 for p in players}

    if n <= 10:
        # Exact Shapley via all permutations (feasible up to ~10 players)
        from itertools import permutations
        perms = list(permutations(players))
        rng.shuffle(perms)
        perms_to_use = perms[:n_samples]
    else:
        # Random permutation sampling
        perms_to_use = [rng.permutation(players).tolist() for _ in range(n_samples)]

    for perm in perms_to_use:
        coalition = frozenset()
        prev_val = characteristic_fn(coalition)
        for player in perm:
            coalition = coalition | {player}
            new_val = characteristic_fn(coalition)
            shapley[player] += (new_val - prev_val) / len(perms_to_use)
            prev_val = new_val

    return shapley


def normalize_attributions(raw: Dict[str, float]) -> Dict[str, float]:
    """Convert raw Shapley values to percentage contributions (sum = 100%)."""
    total = sum(abs(v) for v in raw.values())
    if total == 0:
        return {k: 0.0 for k in raw}
    return {k: round(v / total * 100, 2) for k, v in raw.items()}


# ------------------------------------------------------------------ #
#  Built-in characteristic functions for common attribution problems  #
# ------------------------------------------------------------------ #

def marketing_mta_fn(conversion_data: pd.DataFrame) -> Callable:
    """
    Multi-touch attribution characteristic function.
    conversion_data: DataFrame with columns [channel, touchpoint_order, converted]
    Returns v(S) = fraction of conversions where at least one channel in S appeared.
    """
    converted = conversion_data[conversion_data["converted"] == 1]

    def v(coalition: frozenset) -> float:
        if not coalition:
            return 0.0
        mask = converted["channel"].isin(coalition)
        journeys_touched = converted[mask]["journey_id"].nunique()
        total_journeys = converted["journey_id"].nunique()
        return journeys_touched / max(total_journeys, 1)

    return v


def linear_model_fn(X: np.ndarray, y: np.ndarray) -> Callable:
    """
    Characteristic function based on R^2 gain from feature subsets.
    v(S) = R^2 of OLS regression using only features in S.
    """
    from sklearn.linear_model import LinearRegression
    from sklearn.metrics import r2_score

    def v(coalition: frozenset) -> float:
        if not coalition:
            return 0.0
        idx = list(coalition)
        model = LinearRegression().fit(X[:, idx], y)
        return max(r2_score(y, model.predict(X[:, idx])), 0.0)

    return v


# ------------------------------------------------------------------ #
#  Preprocessing helpers                                              #
# ------------------------------------------------------------------ #

def handle_outliers(df: pd.DataFrame, method: str = "iqr",
                    factor: float = 1.5) -> pd.DataFrame:
    """
    Clip outliers using IQR fencing or Z-score capping.
    method: 'iqr' or 'zscore'
    Returns cleaned DataFrame with outliers replaced by boundary values.
    """
    df = df.copy()
    numeric_cols = df.select_dtypes(include=np.number).columns
    for col in numeric_cols:
        if method == "iqr":
            q1, q3 = df[col].quantile([0.25, 0.75])
            iqr = q3 - q1
            lo, hi = q1 - factor * iqr, q3 + factor * iqr
        else:  # zscore
            mu, sigma = df[col].mean(), df[col].std()
            lo, hi = mu - factor * sigma, mu + factor * sigma
        clipped = df[col].clip(lo, hi)
        n_clipped = (df[col] != clipped).sum()
        if n_clipped:
            print(f"  {col}: clipped {n_clipped} outliers [{lo:.2f}, {hi:.2f}]")
        df[col] = clipped
    return df


def handle_missing(df: pd.DataFrame, strategy: str = "median",
                   threshold: float = 0.5) -> pd.DataFrame:
    """
    Two-phase missing-value handling:
      1. Drop columns where missingness > threshold
      2. Impute remaining with strategy (mean / median / mode / knn)
    """
    df = df.copy()
    miss_rate = df.isnull().mean()
    drop_cols = miss_rate[miss_rate > threshold].index.tolist()
    if drop_cols:
        print(f"  Dropping {len(drop_cols)} columns with >{threshold:.0%} missing: {drop_cols}")
        df = df.drop(columns=drop_cols)

    numeric_cols = df.select_dtypes(include=np.number).columns
    if strategy == "knn":
        from sklearn.impute import KNNImputer
        imp = KNNImputer(n_neighbors=5)
        df[numeric_cols] = imp.fit_transform(df[numeric_cols])
    else:
        fill_fn = {"mean": df[numeric_cols].mean, "median": df[numeric_cols].median}
        fills = fill_fn.get(strategy, df[numeric_cols].median)()
        df[numeric_cols] = df[numeric_cols].fillna(fills)
    print(f"  Imputed remaining missing values with strategy='{strategy}'")
    return df


def clean_dataset(df: pd.DataFrame,
                  outlier_method: str = "iqr",
                  impute_strategy: str = "median",
                  drop_missing_threshold: float = 0.5,
                  drop_correlated_threshold: float = 0.95) -> pd.DataFrame:
    """Full cleaning pipeline: outliers -> missing -> correlation -> type coercion."""
    print(f"Input shape: {df.shape}")
    df = handle_outliers(df, method=outlier_method)
    df = handle_missing(df, strategy=impute_strategy, threshold=drop_missing_threshold)

    # Remove highly correlated features (keep first of each pair)
    numeric = df.select_dtypes(include=np.number)
    corr = numeric.corr().abs()
    upper = corr.where(np.triu(np.ones(corr.shape), k=1).astype(bool))
    drop_cols = [c for c in upper.columns if any(upper[c] > drop_correlated_threshold)]
    if drop_cols:
        print(f"  Dropping {len(drop_cols)} highly correlated columns: {drop_cols}")
        df = df.drop(columns=drop_cols)

    print(f"Output shape: {df.shape}")
    return df
